
#include "stdafx.h"
#include "Compiler.h"
#include "Test.h"

using namespace std;
bool kkli::Debug::OUTPUT_TO_CONSOLE = true;

int main()
{
	auto showHelp = [] {
		std::cout << "\n-test: run test files." << std::endl;
		std::cout << "-gen: show code generated." << std::endl;
		std::cout << "-gg: show code generated by global declarations." << std::endl;
		std::cout << "-e: show executed instructions." << std::endl;
		std::cout << "-ev: show executed instructions and register values" << std::endl;
		std::cout << "-nw: no warnings." << std::endl;
		std::cout << "-dt1: show compile details (level-1)." << std::endl;
		std::cout << "-dt2: show compile details (level-2)." << std::endl;
		std::cout << "-dt3: show compile details (level-3)." << std::endl;
		std::cout << "-df: write debug info to debug.txt." << std::endl;
	};

	while (true) {

		//init
		kkli::Debug::clear();
		DEBUG_INFO->reset();
		bool isHelpMode = false;
		bool isCmd = false;

		std::cout << ">> ";
		string str;
		while (true) {
			cin >> str;

			//清屏命令
			if (str == "cls") {
				system("cls");
				isCmd = true;
				break;
			}

			//查看支持的指令
			if (str == "-help") {
				showHelp();
				isHelpMode = true;
				break;
			}
			//测试模式
			if (str == "-test") {
				DEBUG_INFO->setTestMode();
				break;
			}
			//查看生成的代码
			else if (str == "-gen") {
				DEBUG_INFO->setInstGenMode();
			}
			//查看每个全局定义生成的代码
			else if (str == "-gg") {
				DEBUG_INFO->setGlobalDeclInstGenMode();
			}
			//查看代码执行过程
			else if (str == "-e") {
				DEBUG_INFO->seeCodeExecute();
			}
			//查看代码执行过程中的值 （ax=...）
			else if (str == "-ev") {
				DEBUG_INFO->seeCodeExecuteDetail();
			}
			//无视warning模式（不输出warning）
			else if (str == "-nw") {
				DEBUG_INFO->ignoreWarning();
			}
			//一般详细模式
			else if (str == "-dt1") {
				DEBUG_INFO->setDetail1Mode();
			}
			//十分详细模式
			else if (str == "-dt2") {
				DEBUG_INFO->setDetail2Mode();
			}
			//最详细模式
			else if (str == "-dt3") {
				DEBUG_INFO->setDetail3Mode();
			}
			//debug信息输出到debug.txt文件
			else if (str == "-df") {
				kkli::Debug::OUTPUT_TO_CONSOLE = false;
			}
			//避免乱来
			else if (cin.bad()) {
				cin.clear();
				cin.ignore(numeric_limits<std::streamsize>::max(), '\n');
				cout << "can't open: " << str << ", please input again." << endl;
			}
			//输入的是文件名
			else break;
		}

		try {
			//cmd命令
			if (isCmd) {}

			else {
				//查看帮助
				if (isHelpMode) {}

				//测试
				else if (DEBUG_INFO->IS_TEST_MODE) {
					kkli::Test::getInstance()->run();
				}

				//编译文件
				else {
					kkli::Compiler compiler(str);
					compiler.run();
				}

				std::cout << "\n\n";
			}
		}
		catch (const kkli::Error& err) {
			cout << err.what() << endl;
		}
	}

	system("pause");
    return 0;
}
